import { ProductService } from '@/application/product/services/product.service';
import { BaseProductController } from './base-product.controller';
import type { CreateProductDto, UpdateProductDto, GetListProductDto, UpdateProductStockPriceDto, GetProductByIdQueryDto } from '@/application/product/dtos';
export declare class ProductAdminController extends BaseProductController {
    protected readonly productService: ProductService;
    constructor(productService: ProductService);
    getProductById(id: string, query: GetProductByIdQueryDto): Promise<{
        productId: string;
        categoryId: string;
        name: string;
        description: string | null;
        thumbnail: string | null;
        createdAt: Date;
        updatedAt: Date;
        options: {
            optionId: string;
            productId: string;
            name: string;
            slug: string;
            color: string;
            colorFamily: string;
            thumbnail: string | null;
            images: string[];
            price: number;
            newPrice: number | null;
            outOfStock: boolean;
            isShow: boolean;
            search: string;
            createdAt: Date;
            updatedAt: Date;
            hasDiscount: boolean;
            discountPercentage: number | null;
            variants: {
                variantId: string;
                optionId: string;
                sku: string;
                size: string;
                price: number;
                newPrice: number | null;
                stockQuantity: number;
                createdAt: Date;
                updatedAt: Date;
                hasDiscount: boolean;
                discountPercentage: number | null;
                inStock: boolean;
                lowStock: boolean;
            }[] | undefined;
        }[] | undefined;
    }>;
    getAllProducts(query: GetListProductDto): Promise<{
        items: {
            productId: string;
            categoryId: string;
            name: string;
            description: string | null;
            thumbnail: string | null;
            createdAt: Date;
            updatedAt: Date;
            options: {
                optionId: string;
                productId: string;
                name: string;
                slug: string;
                color: string;
                colorFamily: string;
                thumbnail: string | null;
                images: string[];
                price: number;
                newPrice: number | null;
                outOfStock: boolean;
                isShow: boolean;
                search: string;
                createdAt: Date;
                updatedAt: Date;
                hasDiscount: boolean;
                discountPercentage: number | null;
                variants: {
                    variantId: string;
                    optionId: string;
                    sku: string;
                    size: string;
                    price: number;
                    newPrice: number | null;
                    stockQuantity: number;
                    createdAt: Date;
                    updatedAt: Date;
                    hasDiscount: boolean;
                    discountPercentage: number | null;
                    inStock: boolean;
                    lowStock: boolean;
                }[] | undefined;
            }[] | undefined;
        }[];
        nextCursor: string | null;
    }>;
    createProduct(createProductDto: CreateProductDto): Promise<{
        productId: string;
        categoryId: string;
        name: string;
        description: string | null;
        thumbnail: string | null;
        createdAt: Date;
        updatedAt: Date;
        options: {
            optionId: string;
            productId: string;
            name: string;
            slug: string;
            color: string;
            colorFamily: string;
            thumbnail: string | null;
            images: string[];
            price: number;
            newPrice: number | null;
            outOfStock: boolean;
            isShow: boolean;
            search: string;
            createdAt: Date;
            updatedAt: Date;
            hasDiscount: boolean;
            discountPercentage: number | null;
            variants: {
                variantId: string;
                optionId: string;
                sku: string;
                size: string;
                price: number;
                newPrice: number | null;
                stockQuantity: number;
                createdAt: Date;
                updatedAt: Date;
                hasDiscount: boolean;
                discountPercentage: number | null;
                inStock: boolean;
                lowStock: boolean;
            }[] | undefined;
        }[] | undefined;
    } | undefined>;
    updateProduct(id: string, updateProductDto: UpdateProductDto): Promise<{
        productId: string;
        categoryId: string;
        name: string;
        description: string | null;
        thumbnail: string | null;
        createdAt: Date;
        updatedAt: Date;
        options: {
            optionId: string;
            productId: string;
            name: string;
            slug: string;
            color: string;
            colorFamily: string;
            thumbnail: string | null;
            images: string[];
            price: number;
            newPrice: number | null;
            outOfStock: boolean;
            isShow: boolean;
            search: string;
            createdAt: Date;
            updatedAt: Date;
            hasDiscount: boolean;
            discountPercentage: number | null;
            variants: {
                variantId: string;
                optionId: string;
                sku: string;
                size: string;
                price: number;
                newPrice: number | null;
                stockQuantity: number;
                createdAt: Date;
                updatedAt: Date;
                hasDiscount: boolean;
                discountPercentage: number | null;
                inStock: boolean;
                lowStock: boolean;
            }[] | undefined;
        }[] | undefined;
    } | undefined>;
    updateProductStockPrice(id: string, updateStockPriceDto: UpdateProductStockPriceDto): Promise<{
        success: boolean;
    }>;
    deleteProduct(id: string): Promise<{
        message: string;
    }>;
}
