export declare enum EPermission {
    'CATEGORY_MANAGEMENT' = "CATEGORY_MANAGEMENT",
    'PRODUCT_MANAGEMENT' = "PRODUCT_MANAGEMENT",
    'ORDER_MANAGEMENT' = "ORDER_MANAGEMENT",
    'USER_MANAGEMENT' = "USER_MANAGEMENT",
    'ROLE_MANAGEMENT' = "ROLE_MANAGEMENT",
    'DASHBOARD_ACCESS' = "DASHBOARD_ACCESS",
    'IMAGE_MANAGEMENT' = "IMAGE_MANAGEMENT"
}
