---
config:
  look: neo
  theme: default
---
classDiagram
    namespace Dashboard {
        class DashboardAdminController {
            +getOrderStatistics(query)
            +getRevenueStatistics(query)
        }
    }
