import { ProductVariantEntity } from './product-variant.entity';
export declare class ProductOptionEntity {
    readonly optionId: string;
    productId: string;
    name: string;
    slug: string;
    color: string;
    colorFamily: string;
    images: string[];
    price: number;
    newPrice: number;
    outOfStock: boolean;
    isShow: boolean;
    search: string;
    readonly createdAt: Date;
    updatedAt: Date;
    variants?: ProductVariantEntity[] | undefined;
    constructor(optionId: string, productId: string, name: string, slug: string, color: string, colorFamily: string, images: string[], price: number, newPrice: number, outOfStock: boolean, isShow: boolean, search: string, createdAt: Date, updatedAt: Date, variants?: ProductVariantEntity[] | undefined);
    getDisplayPrice(): number;
    hasDiscount(): boolean;
    getDiscountPercentage(): number | null;
    getThumbnail(): string | null;
    toJSON(): {
        optionId: string;
        productId: string;
        name: string;
        slug: string;
        color: string;
        colorFamily: string;
        thumbnail: string | null;
        images: string[];
        price: number;
        newPrice: number | null;
        outOfStock: boolean;
        isShow: boolean;
        search: string;
        createdAt: Date;
        updatedAt: Date;
        hasDiscount: boolean;
        discountPercentage: number | null;
        variants: {
            variantId: string;
            optionId: string;
            sku: string;
            size: string;
            price: number;
            newPrice: number | null;
            stockQuantity: number;
            createdAt: Date;
            updatedAt: Date;
            hasDiscount: boolean;
            discountPercentage: number | null;
            inStock: boolean;
            lowStock: boolean;
        }[] | undefined;
    };
}
